# Generated by Django 4.2.30 on 2026-07-18 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkout_id', models.CharField(blank=True, help_text='Checkout ID from HyperPay', max_length=255, null=True, unique=True)),
                ('merchant_transaction_id', models.CharField(db_index=True, help_text='Unique transaction ID for this payment', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(default='SAR', help_text='Payment currency', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('resource_path', models.TextField(blank=True, help_text='Resource path from HyperPay redirect', null=True)),
                ('hyperpay_response', models.JSONField(blank=True, help_text='Full response from HyperPay', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When payment was verified', null=True)),
                ('booking_id', models.IntegerField(blank=True, help_text='Related booking ID if applicable', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant_transaction_id'], name='payments_pa_merchan_83f625_idx'), models.Index(fields=['checkout_id'], name='payments_pa_checkou_9e927e_idx'), models.Index(fields=['status'], name='payments_pa_status_b6726a_idx')],
            },
        ),
    ]
