"""Let a resident's national ID fit in the column.

id_num was a 32-bit integer, so the largest value it could hold was
2147483647. Saudi national IDs are ten digits and a resident's begins with 2,
which puts roughly 85% of them above that ceiling. Registration refused every
one of those with a validation error the front end rendered as "an unexpected
error", so those customers simply could not open an account.

Widening is safe in both directions on PostgreSQL: integer -> bigint is a
metadata-only change on modern versions, and every value already stored still
fits if it is ever narrowed back.
"""
# Generated by Django 4.2.30 on 2026-09-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_num',
            field=models.BigIntegerField(null=True),
        ),
    ]
