"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables early so they are available for all settings
load_dotenv(os.path.join(BASE_DIR, '.env'))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-w0qn7x6!%o)%(1dv)hn0w@#ortp6@d-z3(!(4sh6-i_h0k(grh")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "localhost:5173",
    "localhost:5174",
    "localhost:5175",
    "ken.mernantech.com",
    "ken-api.mernantech.com",
    "api.kenluxuryreef.com",
    "kenluxuryreef.com",
    "dash.kenluxuryreef.com",
]

# Allow all hosts or custom hosts in production/Vercel
if os.getenv("ALLOWED_HOSTS"):
    ALLOWED_HOSTS.extend([host.strip() for host in os.getenv("ALLOWED_HOSTS").split(",")])
else:
    ALLOWED_HOSTS.append("*")


# Origins allowed for CSRF validation (scheme + host, e.g. https://dash.example.com)
CSRF_TRUSTED_ORIGINS = [
    "http://dash.kenluxuryreef.com",
    "https://dash.kenluxuryreef.com",
]

if os.getenv("CSRF_TRUSTED_ORIGINS"):
    CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in os.getenv("CSRF_TRUSTED_ORIGINS").split(",")])
else:
    CSRF_TRUSTED_ORIGINS.append("https://*.vercel.app")



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #third party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    
    'corsheaders',
    'ckeditor',
    'phonenumber_field',


    # Apps
    'accounts',
    'products',
    'content',
    'payments',
    
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
     "whitenoise.middleware.WhiteNoiseMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
]

from datetime import timedelta 


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
         'accounts.authentication.CustomJWTAuthentication',
    ),
   
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'TOKEN_BLACKLIST_ENABLED': True,

    'ALGORITHM': 'HS256',

    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}
ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR,'templates')],

        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database Configuration
# Support PostgreSQL (Supabase/Neon) via DATABASE_URL or fallback to SQLite
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    import dj_database_url
    # Ensure SSL mode is enabled for Supabase / Neon / remote PostgreSQL
    ssl_require = "localhost" not in DATABASE_URL and "127.0.0.1" not in DATABASE_URL
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=ssl_require
        )
    }
elif os.getenv("DATABASE_ENGINE") == "django.db.backends.postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DATABASE_NAME"),
            "USER": os.getenv("DATABASE_USER"),
            "PASSWORD": os.getenv("DATABASE_PASSWORD"),
            "HOST": os.getenv("DATABASE_HOST", "localhost"),
            "PORT": os.getenv("DATABASE_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Media files for uploads (Use /tmp on Vercel serverless read-only filesystem)
MEDIA_URL = "/media/"
if os.getenv("VERCEL") or os.getenv("DATABASE_URL"):
    MEDIA_ROOT = "/tmp/media"
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Enable WhiteNoise to serve compressed files
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_USER_MODEL = 'accounts.User'

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "https://ken.mernantech.com",
    "https://ken-api.mernantech.com",
    "https://api.kenluxuryreef.com",
    "https://kenluxuryreef.com",
    "https://dash.kenluxuryreef.com",
    "http://dash.kenluxuryreef.com",
    "http://localhost:8080",
    "http://127.0.0.1:9000",
    "http://localhost:3000",
]
CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

import os
from django.core.mail import send_mail


# Frontend / site base URL for emails and links (no trailing slash).
# Override via FRONTEND_BASE_URL (e.g. https://dash.kenluxuryreef.com or http://localhost:3000).
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "https://ken.mernantech.com")

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'maisalama2009@gmail.com'  # Your Gmail address
# EMAIL_HOST_PASSWORD =  'ygqy njcp fycm mmvv' # Your Gmail password or app password
EMAIL_HOST_USER = "mernandev@gmail.com"
EMAIL_HOST_PASSWORD = "jfcxprwtjykdexfm"

# EMAIL_HOST_USER = "info@kenluxuryreef.com"
# EMAIL_HOST_PASSWORD = "g44GY4yw4yw$Y"



DAFTRA_API_KEY = 'b376d2303a2d26546d08b33953f898f8527f713e' 
DAFTRA_BASE_URL = 'https://bestoffer.daftra.com'

# HyperPay/OPPWA Payment Gateway Settings
# Production credentials (default)
OPPWA_BASE_URL = os.getenv('OPPWA_BASE_URL', 'https://eu-prod.oppwa.com')
OPPWA_ACCESS_TOKEN = os.getenv('OPPWA_ACCESS_TOKEN', 'OGFjOWE0Y2M5YWUzZGYzZDAxOWIwYzdlYjVmODRlZjl8aFd3V21AdWpVOSFTS3gleUVENU0=')
OPPWA_ENTITY_ID = os.getenv('OPPWA_ENTITY_ID', '8ac9a4cc9ae3df3d019b0c80be3d4f12')

# Development/Test credentials (for testing - set OPPWA_USE_DEV=True to use)
OPPWA_DEV_BASE_URL = 'https://eu-test.oppwa.com'
OPPWA_DEV_ACCESS_TOKEN = 'OGFjN2E0Yzc5YTZhOWZiNzAxOWE2Y2RiMTA5NTAyMWF8VGNaQTVvZXpHNEpoUUBXSEM2UDg='
OPPWA_DEV_ENTITY_ID = '8ac7a4c79a6a9fb7019a6cdb6d2e021e'

# Use dev credentials if OPPWA_USE_DEV environment variable is set to 'True'
OPPWA_USE_DEV = os.getenv('OPPWA_USE_DEV', 'False').lower() == 'true'
if OPPWA_USE_DEV:
    OPPWA_BASE_URL = OPPWA_DEV_BASE_URL
    OPPWA_ACCESS_TOKEN = OPPWA_DEV_ACCESS_TOKEN
    OPPWA_ENTITY_ID = OPPWA_DEV_ENTITY_ID



