# Generated by Django 4.2.30 on 2026-07-18 19:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('min_purchasable_quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('max_purchasable_quantity', models.IntegerField(blank=True, default=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableDateService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('min_purchasable_quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('max_purchasable_quantity', models.IntegerField(blank=True, default=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('persons_max_num', models.IntegerField()),
                ('paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('not_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('kids_max_num', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('paid', 'paid'), ('refuned', 'refuned')], default='pending', max_length=255)),
                ('qr_code', models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to=products.models.qr_image)),
                ('is_qr_genereated', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('invoice_url', models.URLField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_scaned', models.CharField(choices=[('not_started', 'not_started'), ('scaned', 'scaned'), ('not_valid', 'not_valid')], default='not_started', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.event_image)),
                ('min_purchasable_quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('max_purchasable_quantity', models.IntegerField(blank=True, default=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('available_dates', models.ManyToManyField(blank=True, null=True, related_name='events', to='products.availabledateevent')),
            ],
        ),
        migrations.CreateModel(
            name='Hut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('size', models.CharField(choices=[('small', 'small'), ('meduim', 'meduim'), ('large', 'large')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=products.models.hut_image)),
                ('max_kids_num', models.IntegerField(blank=True, null=True)),
                ('bedrooms_num', models.IntegerField(blank=True, null=True)),
                ('bathrooms_num', models.IntegerField(blank=True, null=True)),
                ('max_persons_num', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('macc_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HutImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.hut_image)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.icons)),
            ],
        ),
        migrations.CreateModel(
            name='KenSpecialItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.event_image)),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('min_purchasable_quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('max_purchasable_quantity', models.IntegerField(blank=True, default=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('huts', models.ManyToManyField(blank=True, null=True, to='products.hut')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ken_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('address_ar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_ar', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=products.models.icons)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.event_image)),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity', models.IntegerField()),
                ('min_purchasable_quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('max_purchasable_quantity', models.IntegerField(blank=True, default=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('available_dates', models.ManyToManyField(blank=True, null=True, related_name='services', to='products.availabledateservice')),
                ('hut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.hut')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialItemTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_extra', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_items', to='products.booking')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.kenspecialitems')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('is_extra', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='products.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.services')),
            ],
        ),
        migrations.CreateModel(
            name='QrLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('check_in', 'check_in'), ('check_out', 'check_out')], max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.booking')),
            ],
        ),
        migrations.CreateModel(
            name='HutRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField(blank=True, null=True)),
                ('is_testmonail', models.BooleanField(default=True)),
                ('hut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.hut')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HutMainService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('description_ar', models.TextField()),
                ('is_extra', models.BooleanField(default=False)),
                ('hut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_services', to='products.hut')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hut_main_services', to='products.icon')),
            ],
        ),
        migrations.CreateModel(
            name='HutIncludes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=products.models.icons)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('hut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includes', to='products.hut')),
            ],
        ),
        migrations.CreateModel(
            name='HutActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('description_ar', models.TextField()),
                ('hut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='products.hut')),
            ],
        ),
        migrations.AddField(
            model_name='hut',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='products.hutimages'),
        ),
        migrations.AddField(
            model_name='hut',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.location'),
        ),
        migrations.AddField(
            model_name='hut',
            name='promocode',
            field=models.ManyToManyField(blank=True, null=True, to='products.promocode'),
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('is_extra', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='products.booking')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('description_ar', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_note', to='products.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('description_ar', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_include', to='products.event')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_icon', to='products.icon')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='hut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.hut'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.location'),
        ),
        migrations.AddField(
            model_name='event',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DaftraInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_url', models.URLField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daftra_invoice', to='products.booking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_extra', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='products.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='hut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='products.hut'),
        ),
        migrations.AddField(
            model_name='booking',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.promocode'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AvailableDateRanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=255, null=True)),
                ('precentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('huts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='products.hut')),
            ],
        ),
    ]
