# Generated by Django 4.2.30 on 2026-07-25 23:31

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=products.models.event_image),
        ),
        migrations.AlterField(
            model_name='hut',
            name='main_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=products.models.hut_image),
        ),
        migrations.AlterField(
            model_name='hutimages',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=products.models.hut_image),
        ),
        migrations.AlterField(
            model_name='hutincludes',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=products.models.icons),
        ),
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.ImageField(max_length=500, upload_to=products.models.icons),
        ),
        migrations.AlterField(
            model_name='kenspecialitems',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=products.models.event_image),
        ),
        migrations.AlterField(
            model_name='note',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=products.models.icons),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=products.models.event_image),
        ),
    ]
