# Generated by Django 4.2.30 on 2026-08-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_event_image_alter_hut_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledateevent',
            name='date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='availabledateevent',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='availabledateranges',
            name='date_from',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='availabledateranges',
            name='date_to',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='availabledateservice',
            name='date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='availabledateservice',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('paid', 'paid'), ('refuned', 'refuned')], db_index=True, default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookingdate',
            name='date_from',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bookingdate',
            name='date_to',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='hut',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='hut',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='kenspecialitems',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='kenspecialitems',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
