# Generated by Django 4.2.30 on 2026-08-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_booking_guest_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('partially_paid', 'partially_paid'), ('cancelled', 'cancelled'), ('paid', 'paid'), ('refuned', 'refuned')], db_index=True, default='pending', max_length=255),
        ),
    ]
