# Generated by Django 4.2.30 on 2026-08-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_booking_partial_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftrainvoice',
            name='daftra_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
