# Generated by Django 4.2.30 on 2026-08-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_daftra_invoice_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftrainvoice',
            name='qr_code_png',
            field=models.TextField(blank=True, help_text='base64 PNG', null=True),
        ),
        migrations.AddField(
            model_name='daftrainvoice',
            name='qr_code_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
