# Generated by Django 4.2.30 on 2026-08-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_daftra_invoice_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='hut',
            name='weekday_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hut',
            name='weekend_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
