# Generated by Django 4.2.30 on 2026-08-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_seed_hut_weekday_weekend_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
